export enum ContainerTag {
    CONTROLLER,
    QUERY_HANDLER,
    COMMAND_HANDLER,
    EVENT_SUBSCRIBER,
    MIDDLEWARE,
    ERROR_MIDDLEWARE,
    COMMAND_EXECUTOR,
    QUERY_EXECUTOR,
    EVENT_EXECUTOR,
}
