services:

  Auth.infrastructure.LoginController:
    class: ../../../modules/auth/infrastructure/controllers/AuthenticateController
    arguments: ['@App.QueryBus']
    tags:
      - { name: controller }

  Auth.app.Authenticator:
    class: ../../../modules/auth/application/login/Authenticator
    arguments: ['@Auth.domain.AuthUserRepository', '@Auth.domain.AuthTokenRepository', '@App.EventBus']

  Auth.app.AuthenticateQueryHandler:
    class: ../../../modules/auth/application/login/AuthenticateQueryHandler
    arguments: ['@Auth.app.Authenticator']
    tags:
      - { name: queryHandler }

  Auth.domain.AuthUserRepository:
    class: ../../../modules/auth/infrastructure/persistence/TypeOrmAuthUserRepository
    arguments: ['@App.ConnectionManager']

  Auth.domain.AuthTokenRepository:
    class: ../../../modules/auth/infrastructure/generators/JwtAuthTokenRepository
    arguments: ['@App.Env']

#  App.Courses.application.CourseCreator:
#    class: ../../../../../Contexts/Mooc/Courses/application/CourseCreator
#    arguments: [ '@Mooc.Courses.domain.AuthUserRepository' ]
