export const Keys = {
    App: {
        Env: Symbol.for('Env'),
        Logger: Symbol.for('Log'),
        ControllerDiscoverer: Symbol.for('ControllerDiscoverer'),
        MiddlewareDiscoverer: Symbol.for('MiddlewareDiscoverer'),
        ErrorMiddlewareDiscoverer: Symbol.for('ErrorMiddlewareDiscoverer'),
        ErrorTracker: Symbol.for('ErrorTracker'),
        MessageStore: Symbol.for('MessageStore'),
        PersistErrorMiddleware: Symbol.for('PersistErrorMiddleware'),
        HttpErrorMiddleware: Symbol.for('HttpErrorMiddleware'),
        StoreMessageBusMiddleware: Symbol.for('StoreMessageBusMiddleware'),
        TimeBusMiddleware: Symbol.for('TimeBusMiddleware'),
        AuthMiddleware: Symbol.for('AuthMiddleware'),
        ServerOpenApiConfig: Symbol.for('ServerOpenApiConfig'),
        ConnectionManager: Symbol.for('ConnectionManager'),
        AppConfig: Symbol.for('AppConfig'),
    },
    CQRS: {
        CommandHandlersMapper: Symbol.for('CommandHandlersMapper'),
        CommandBus: Symbol.for('CommandBus'),
        QueryHandlersMapper: Symbol.for('QueryHandlersMapper'),
        QueryBus: Symbol.for('QueryBus'),
        EventSubscriberMapper: Symbol.for('EventSubscriberMapper'),
        EventBus: Symbol.for('EventBus'),
        RabbitMqConfig: Symbol.for('RabbitMqConfig'),
        EventDeserializer: Symbol.for('EventDeserializer'),
        EventClassMapper: Symbol.for('EventClassMapper'),
        EventStore: Symbol.for('EventStore'),
        EventStoreController: Symbol.for('EventStoreController'),
    },
    Test: {
        EnvironmentArranger: Symbol.for('EnvironmentArranger'),
        EnvironmentFixtures: Symbol.for('EnvironmentFixtures'),
    },
    Info: {
        InfoController: Symbol.for('InfoController'),
        SetInfoController: Symbol.for('SetInfoController'),
        InfoService: Symbol.for('InfoService'),
        SetInfoService: Symbol.for('SetInfoService'),
        SendEmailService: Symbol.for('SendEmailService'),
        InfoQueryHandler: Symbol.for('InfoQueryHandler'),
        SetInfoCommandHandler: Symbol.for('SetInfoCommandHandler'),
        SendEmailInfoRequestDomainEventSubscriber: Symbol.for('SendEmailInfoRequestDomainEventSubscriber'),
    },
    Auth: {
        AuthenticateController: Symbol.for('AuthenticateController'),
        Authenticator: Symbol.for('Authenticator'),
        AuthenticateQueryHandler: Symbol.for('AuthenticateQueryHandler'),
        AuthUserRepository: Symbol.for('AuthUserRepository'),
        AuthTokenRepository: Symbol.for('AuthTokenRepository'),
    },
    Bike: {
        BikeRepository: Symbol.for('BikeRepository'),

        BikeCreator: Symbol.for('BikeCreator'),
        BikeCreatorCommandHandler: Symbol.for('BikeCreatorCommandHandler'),
        BikeCreatorController: Symbol.for('BikeCreatorController'),

        BikeList: Symbol.for('BikeList'),
        BikeListQueryHandler: Symbol.for('BikeListQueryHandler'),
        BikeListController: Symbol.for('BikeListController'),

        BikeDetail: Symbol.for('BikeDetail'),
        BikeDetailQueryHandler: Symbol.for('BikeDetailQueryHandler'),
        BikeDetailController: Symbol.for('BikeDetailController'),

        BikeModify: Symbol.for('BikeModify'),
        BikeModifyCommandHandler: Symbol.for('BikeModifyCommandHandler'),
        BikeModifyController: Symbol.for('BikeModifyController'),
    },
}
